### ISSUE TITLE
Disco benchmark

### ISSUE THREAD

**Issue by Nacho114** [epfml/disco#261]
As suggested by @martinjaggi, it would be good to have a performance benchmark of certain tasks, that way when we start trying out different things we see how performance is affected. 

At a first time performance will be mainly in terms of prediction accuracy, but we should also include run time performance in order to see what the bottle necks are. 

The idea is to have a `benchmark/` folder living at the `mobile-...`, it will be similar to the `tests` folder except we want to know how well it works (rather than the simple question of "does it work?").

The first benchmark will be on [face detection](https://www.kaggle.com/frabbisw/facial-age) since this is also useful for our start up collaborators. We can then extend this to include CIFAR-10 and other standard data sets.

To make this extendable for future use we will create a simple infrastructure that allows to simulate several clients.

**Comment by dgengler6** [comment]
That is really great, I was talking about it at the beginning of the semester because it would be great for performance evaluations of personalization schemes ! 

I think it's really important that it generates log files so we can plot that and have a use for it ! 

I can give you a hand if you want @Nacho114 !

**Comment by Nacho114** [comment]
Great 😃, we can discuss this when we meet later!

**Comment by s314cy** [comment]
Linked to #240.
