### ISSUE TITLE
"Variable with name conv2d_Cov2D1/kernel was already registered" error

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#379]
Error when "train locally" selected after "train collaboratively" 
Note: train collaboratively did not work and thus may be dependent on issue #378

![Screenshot 2022-07-14 at 00 54 55](https://user-images.githubusercontent.com/62021543/178852038-9031ccaa-6405-4765-a848-271e7abf6c8c.png)

**Comment by Nacho114** [comment]
Very likely related to #371

**Comment by Nacho114** [comment]
Additional info helpful for debugging:

I tried to reproduce this, so within the same script I loaded a model twice and had no such error; when loading the second model, the tfjs engine is aware of the previous model, and so gives the second model different variable names (to avoid collision).

I have observed the same error when loading a model from the benchmark script and then briefly after in the server. The collision appears to happen somehow because the engine does not change the variable names of the second model.
