### ISSUE TITLE
Adjust `Create Your Own Task` button in Tutorial

### ISSUE THREAD

**Issue by Annie-LiGHT** [epfml/disco#398]
In the [Tutorial](https://epfml.github.io/disco/#/tutorial) the CREATE YOUR OWN TASK button is still there and navigates to a [broken page](https://epfml.github.io/disco/#/create)

**Comment by martinjaggi** [comment]
yes we should be transparent about this, especially because it's one of the most important functionalities of disco.

i was suggesting to get the old task creation form visible again if that button is pressed (as it showed most useful fields needed, to get an idea), but put a big red warning message on top of it saying that there is an issue (and link to the github issue)

**Comment by martinjaggi** [comment]
same in the _getting started_ page from home also
